// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUdBAjdYRsTishA6IAFitZNIuMP8YoPs',
    appId: '1:835879129455:web:b646c7d5c7417fe52c589a',
    messagingSenderId: '835879129455',
    projectId: 'double-database-eced1',
    authDomain: 'double-database-eced1.firebaseapp.com',
    storageBucket: 'double-database-eced1.appspot.com',
    measurementId: 'G-MKVRHHHBZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk333uNcqFYa1J880VoeMcVRwZrmsZaTQ',
    appId: '1:835879129455:android:b9bc6a3dbf689f7c2c589a',
    messagingSenderId: '835879129455',
    projectId: 'double-database-eced1',
    storageBucket: 'double-database-eced1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB41dOlw_Tm-C9af-azYVI52og_reiWdBg',
    appId: '1:835879129455:ios:dd882ffcbed307b92c589a',
    messagingSenderId: '835879129455',
    projectId: 'double-database-eced1',
    storageBucket: 'double-database-eced1.appspot.com',
    iosBundleId: 'com.example.doubleDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB41dOlw_Tm-C9af-azYVI52og_reiWdBg',
    appId: '1:835879129455:ios:64fb4b16659882862c589a',
    messagingSenderId: '835879129455',
    projectId: 'double-database-eced1',
    storageBucket: 'double-database-eced1.appspot.com',
    iosBundleId: 'com.example.doubleDatabase.RunnerTests',
  );
}
